# script: 'ci/travis.rb'
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
notifications:
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#dradis"
bundler_args: --path vendor/bundle
before_script:
  - "cp config/database.yml.template config/database.yml"
  - "mkdir -p tmp/attachments/"
  - "touch config/first_login.txt"
script: "RAILS_ENV=test bundle exec rake dradis:test:ci --trace"
