# travis.yml for testing radare2. Initially written in 2014, by jn__.

os:
  - linux
  - osx

language: c

compiler:
  - gcc
  - clang

matrix:
  exclude:
      - os: osx
        compiler: gcc

sudo: false

addons:
  apt:
    packages:
      - dc
      - binutils
      - cabextract

cache:
  - ccache
  - apt

script:
  - git clone --depth 1 `doc/repo REGRESSIONS`
  - ./configure --prefix=`pwd`/install > /dev/null
  - make -s -j2 > /dev/null
  - make install > /dev/null
  - export PATH=${TRAVIS_BUILD_DIR}/install/bin:${PATH}
  - export LD_LIBRARY_PATH=${TRAVIS_BUILD_DIR}/install/lib:${LD_LIBRARY_PATH}
  - export LIBR_INCLUDE=${TRAVIS_BUILD_DIR}/libr/include
  - export LIBR_UTIL=${TRAVIS_BUILD_DIR}/libr/util
  - export NOOK=1
  - export NOREPORT=1
  - cd radare2-regressions
  - VERBOSE=1 make -k all
  - make unit_tests

notifications:
  irc: "chat.freenode.net#radare"
  on_success: never
  on_failure: always
